### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by runegan** [docsforadobe/aequery#15]
**[Original report](https://bitbucket.org/motiondesign/aequery/issue/15) by Rune Gangsø (Bitbucket: [runegan](https://bitbucket.org/runegan), GitHub: [runegan](https://github.com/runegan)).**

----------------------------------------

Is there some way to do unit testing for extendscript? I think it is important to have a way to test all the functions, to make sure there is no errors.
I haven't done any unit testing before, so I am not sure how it should be done. Is there anyone who know how this could be done?

**Comment by zlovatt** [comment]
Already implemented!
