### ISSUE TITLE
Wrong links in Docs Menu

### ISSUE THREAD

**Issue by tilles80** [docsforadobe/aequery#68]
hey guys!
first of all, thanks for your work on doing this framework.

An issue I have is that the main menu of the documentation has some broken links.
I think it's just for COMP and LAYER sections. The link has an extra "_" before ".html" ... if you remove this, you can see the page.

Some examples:
https://aenhancers.github.io/aequery/aeq.Comp_.html#forEachLayer
https://aenhancers.github.io/aequery/aeq.Layer_.html#addEffect

cheers

**Comment by zlovatt** [comment]
Yes-- this is due to the docs being autogenerated, and an internal conflict between the "aeq.comp" collection of functions and the "aeq.Comp" extended object. I don't know if there's a great fix for it just yet, but maybe this extra context is helpful? 😅

**Comment by matt-volp** [comment]
Removing the `_` doesnt seem to work any more — any ideas?

**Comment by zlovatt** [comment]
> Removing the `_` doesnt seem to work any more — any ideas?

The root url has changed from `aenhancers.` to `docsforadobe.` – https://docsforadobe.github.io/aequery/aeq.Comp.html#forEachLayer

**Comment by zlovatt** [comment]
Resolved with #71
