### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by runegan** [docsforadobe/aequery#8]
**[Original report](https://bitbucket.org/motiondesign/aequery/issue/8) by Rune Gangsø (Bitbucket: [runegan](https://bitbucket.org/runegan), GitHub: [runegan](https://github.com/runegan)).**

----------------------------------------

A simple project to showcase different ways to use aequery

**Comment by zlovatt** [comment]
There are multiple in the /demo/ folder; closing.
